### ISSUE TITLE
Support for tRPC v10

### ISSUE THREAD

**Issue by samhwang** [toyamarinyon/cloudflare-pages-plugin-trpc#2]
tRPC v10 is now stable, while the plugin and the examples are on the beta v10 version of tRPC :(

**Comment by toyamarinyon** [comment]
Thank you for the issue!
I want to support tRPC v10 too. I have not had time recently because I've been busy working. But I'll keep it by this year.

**Comment by toyamarinyon** [comment]
@samhwang Hi! I've supported tRPC v10 on [0.1.1](https://github.com/toyamarinyon/cloudflare-pages-plugin-trpc/releases/tag/0.1.1). Please check it.

**Comment by samhwang** [comment]
Hey It's working fine for tRPC v10.6.0 now. However I would suggest a few other things:

- Move the `@trpc/server` deps into `devDependencies`, since you only need this in dev
- Add another `peerDependencies` section, and add `@trpc/server` into it. This is so the client project will need to install both `@trpc/server` and this client.

Doing this will make it less likely to break when there are different versions of `@trpc/server` inside the same project creating a mismatch of types.

This is what happens when my project already has `@trpc/server` v10.5.0 and your plugin has v10.6.0. Basically a type mismatch between `trpc` versions.
![Screen Shot 2022-12-22 at 12 59 20 am](https://user-images.githubusercontent.com/4188758/208922731-56211fe3-5013-4bf0-a36d-de9cd1ab4728.png)

Also the docs needs a bit of updating, esp. on the installing part, if you decide to adapt the peer dependency path above.

**Comment by toyamarinyon** [comment]
I encountered the same problem during development and wondered how to fix it.
I see that using `peerDependencies` solves it!  Thank you for teaching!
I'll update the dependencies and the docs.

**Comment by samhwang** [comment]
No worries, I'm glad to help :D

**Comment by toyamarinyon** [comment]
I've reviewed the dependencies and removed the package it's not using. I've also used `peerDependencies` to describe the packages on which this depends.

I've released on [0.1.2](https://github.com/toyamarinyon/cloudflare-pages-plugin-trpc/releases/tag/0.1.2)
