### ISSUE TITLE
Usage in SSR: `cloudflare-pages-plugin-trpc doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module`

### ISSUE THREAD

**Issue by uxduck** [toyamarinyon/cloudflare-pages-plugin-trpc#20]
When trying to build an application that uses tRPC, Cloudflare workers, Astro and this package (`cloudflare-pages-plugin-trpc`), I get an error:
```bash
cloudflare-pages-plugin-trpc doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
{ origin: 'http://localhost:3000' }
```

I've got an MR which tries to get this package installed so that it can use Cloudflare D1: https://github.com/ben-xD/trpc-astro-cloudflare/pull/1. The `main` branch works without `cloudflare-pages-plugin-trpc`.

It seems like we just need to specify `"type": "module"` in `package.json`?

Thanks :)

**Comment by toyamarinyon** [comment]
Thank you for creating issue! 

I'll check it.

**Comment by toyamarinyon** [comment]
@ben-xD It seems that because cloudflare pages builds with `advanced` mode.

Cloudflare Pages Plugin requires to build with `directory` mode.

> For most projects the adapter default of advanced will be sufficient; the dist folder will contain your compiled project. Switching to directory mode allows you to use [pages plugins](https://developers.cloudflare.com/pages/platform/functions/plugins/) such as [Sentry](https://developers.cloudflare.com/pages/platform/functions/plugins/sentry/) or write custom code to enable logging.
> https://docs.astro.build/en/guides/integrations-guide/cloudflare/#mode

I may have time this weekend to address the issue, so I quickly investigated the cause. If @ben-xD can try it, I would like them to give it a try 🙏 

Of corse, if I have time,  try to build with `directory` mode and try to modify code in https://github.com/ben-xD/trpc-astro-cloudflare/pull/1 to works properly.

**Comment by uxduck** [comment]
Thanks for your response. I had gotten it to work without `cloudflare-pages-plugin-trpc` as I wrote  in https://orth.uk/trpc-astro-cloudflare-workers#srctscontextts, using `const runtime = getRuntime<Env>(req);`.

I wasn't able to get it smoothly working and I think my current approach is nicer since it avoids 1 extra third-party dependency. 

Thanks :)
